<?php

namespace Modules\CMS\Database\Seeders;

use Illuminate\Database\Seeder;

class PageTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {


        \DB::table('pages')->delete();

        \DB::table('pages')->insert(array(
            0 =>
            array(
                'id' => 1,
                'name' => 'About Us',
                'slug' => 'about-us',
                'css' => '* { box-sizing: border-box; } body {margin: 0;}#iz8k{padding:10px;margin:0 0 10px 0;}#ifjs{padding:10px;margin:0 0 30px 0;}#ijco{padding:10px;margin:0 0 10px 0;}#ik5t{padding:10px;margin:0 0 30px 0;}#inbk{padding:10px;margin:0 0 10px 0;}#ie1c{padding:10px;margin:0 0 10px 0;}#ipwh{padding:10px;margin:0 0 10px 0;}#icok{padding:10px;margin:0 0 10px 0;}#i94k{padding:10px;margin:0 0 10px 0;}#i1b2u{padding:10px;margin:0 0 30px 0;}#imwjf{padding:10px;margin:0 0 30px 0;}#ihlvo{padding:10px;margin:0 0 30px 0;}#ijkuk{padding:10px;margin:0 0 30px 0;}#ib7ow{padding:10px;margin:0 0 30px 0;}#izl75{padding:10px;margin:0 0 10px 0;}#iiluk{padding:10px;margin:0 0 15px 0;}#izhb9{padding:10px;margin:0 0 10px 0;}#i5bvu{padding:10px;margin:0 0 10px 0;}#iwi92{padding:10px;margin:0 0 30px 0;}#ieavt{padding:10px;margin:0 0 30px 0;}#i325j{padding:10px;margin:0 0 10px 0;}#iwrsl{padding:10px;margin:0 0 10px 0;}#ifv2k{padding:10px;margin:0 0 10px 0;}#ivprk{padding:10px;margin:0 0 10px 0;}#ijnmf{padding:10px;margin:0 0 10px 0;}#isrc5{padding:10px;margin:0 0 10px 0;}#iajog{padding:10px;margin:0 0 30px 0;}#izz1f{padding:10px;margin:0 0 30px 0;}#igvdo{padding:10px;margin:0 0 30px 0;}#ivdq6{padding:10px;margin:0 0 30px 0;}#ih0zr{padding:10px;margin:0 0 30px 0;}#ijo7b{padding:10px;margin:0 0 30px 0;}#ie4ia{padding:10px;margin:0 0 10px 0;}#ikrzn{padding:10px;margin:0 0 30px 0;}',
                'description' => '<body id="izt5"><div id="iz8k"><h1 style="text-align:justify"><strong>Introduction</strong></h1>
                </div><div id="ifjs"><p>Welcome to Artifism, Inc.<br />
                Artifism, Inc. (&ldquo;us&rdquo;, &ldquo;we&rdquo;, or &ldquo;our&rdquo;) operates https://demo.artifism.techvill.net/ (hereinafter referred to as &ldquo;Service&rdquo;).<br />
                Our Privacy Policy governs your visit to https://demo.artifism.techvill.net/, and explains how we collect, safeguard and disclose information that results from your use of our Service.<br />
                By using Service, you agree to the collection and use of information in accordance with this policy. Unless otherwise defined in this Privacy Policy, the terms used in this Privacy Policy have the same meanings as in our Terms and Conditions.<br />
                Our Terms and Conditions (&ldquo;Terms&rdquo;) govern all use of our Service and together with the Privacy Policy constitutes your agreement with us (&ldquo;agreement&rdquo;).</p>
                </div><div id="i5bvu"><h1 style="text-align:justify"><strong>Definitions</strong></h1>
                </div><div id="ieavt"><p>Service means the https://demo.artifism.techvill.net/ website operated by Artifism, Inc.<br />
                Personal Data means data about a living individual who can be identified from those data (or from those and other information either in our possession or likely to come into our possession).<br />
                Usage Data is data collected automatically either generated by the use of Service or from Service infrastructure itself (for example, the duration of a page visit).<br />
                Cookies are small files stored on your device (computer or mobile device).<br />
                Data Controller means a natural or legal person who (either alone or jointly or in common with other persons) determines the purposes for which and the manner in which any personal data are, or are to be, processed. For the purpose of this Privacy Policy, we are a Data Controller of your data.<br />
                Data Processors (on service providers) means any natural or legal person who processes the data on behalf of the Data Controller. We may use the services of various Service Providers in order to process your data more effectively.<br />
                Data Subject is any living individual who is the subject of Personal Data.<br />
                The User is the individual using our Service. The User corresponds to the Data Subject, who is the subject of Personal Data.</p>
                </div><div id="izhb9"><h1 style="text-align:justify"><strong>Information Collection and Use</strong></h1>
                </div><div id="iwi92"><p>We collect several different types of information for various purposes to provide and improve our Service to you.</p>
                </div><div id="izl75"><h1 style="text-align:justify"><strong>Types of Data Collected</strong></h1>
                </div><div id="iiluk"><p><strong>Personal Data</strong><br />
                While using our Service, we may ask you to provide us with certain personally identifiable information that can be used to contact or identify you (&ldquo;Personal Data&rdquo;). Personally identifiable information may include, but is not limited to:</p>

                <p>&nbsp;</p>

                <p>Email address<br />
                First name and last name<br />
                Cookies and Usage Data</p>

                <p>&nbsp;</p>

                <p>We may use your Personal Data to contact you with newsletters, marketing or promotional materials and other information that may be of interest to you. You may opt out of receiving any, or all, of these communications from us by following the unsubscribe link or by emailing at support@artifism.com.</p>

                <p>&nbsp;</p>

                <p><strong>Personal Data</strong><br />
                We may also collect information that your browser sends whenever you visit our Service or when you access Service by or through a mobile device (&ldquo;Usage Data&rdquo;).<br />
                This Usage Data may include information such as your computer&#39;s Internet Protocol address (e.g. IP address), browser type, browser version, the pages of our Service that you visit, the time and date of your visit, the time spent on those pages, unique device identifiers and other diagnostic data.<br />
                When you access Service with a mobile device, this Usage Data may include information such as the type of mobile device you use, your mobile device unique ID, the IP address of your mobile device, your mobile operating system, the type of mobile Internet browser you use, unique device identifiers and other diagnostic data.</p>

                <p>&nbsp;</p>

                <p><strong>Personal Data</strong><br />
                We use cookies and similar tracking technologies to track the activity on our Service and we hold certain information.<br />
                Cookies are files with a small amount of data which may include an anonymous unique identifier. Cookies are sent to your browser from a website and stored on your device. Other tracking technologies are also used such as beacons, tags and scripts to collect and track information and to improve and analyze our Service.<br />
                You can instruct your browser to refuse all cookies or to indicate when a cookie is being sent. However, if you do not accept cookies, you may not be able to use some portions of our Service.</p>

                <p>&nbsp;</p>

                <p>Examples of Cookies we use:<br />
                Session Cookies: We use Session Cookies to operate our Service.<br />
                Preference Cookies: We use Preference Cookies to remember your preferences and various settings.<br />
                Security Cookies: We use Security Cookies for security purposes.<br />
                Advertising Cookies: Advertising Cookies are used to serve you with advertisements that may be relevant to you and your interests.</p>
                </div><div id="icok"><h1 style="text-align:justify"><strong>Use of Data</strong></h1>
                </div><div id="ib7ow"><p>Artifism, Inc. uses the collected data for various purposes:</p>

                <p>&nbsp;</p>

                <p><strong>Personal Data</strong><br />
                to provide and maintain our Service;<br />
                to notify you about changes to our Service;<br />
                to allow you to participate in interactive features of our Service when you choose to do so;<br />
                to provide customer support;<br />
                to gather analysis or valuable information so that we can improve our Service;<br />
                to monitor the usage of our Service;<br />
                to detect, prevent and address technical issues;<br />
                to fulfill any other purpose for which you provide it;<br />
                to carry out our obligations and enforce our rights arising from any contracts entered into between you and us, including for billing and collection;<br />
                to provide you with notices about your account and/or subscription, including expiration and renewal notices, email-instructions, etc.;<br />
                to provide you with news, special offers and general information about other goods, services and events which we offer that are similar to those that you have already purchased or enquired about unless you have opted not to receive such information;<br />
                in any other way we may describe when you provide the information;<br />
                for any other purpose with your consent.</p>
                </div><div id="inbk"><h1 style="text-align:justify"><strong>Retention of Data</strong></h1>
                </div><div id="ik5t"><p>We will retain your Personal Data only for as long as is necessary for the purposes set out in this Privacy Policy. We will retain and use your Personal Data to the extent necessary to comply with our legal obligations (for example, if we are required to retain your data to comply with applicable laws), resolve disputes, and enforce our legal agreements and policies.<br />
                We will also retain Usage Data for internal analysis purposes. Usage Data is generally retained for a shorter period, except when this data is used to strengthen the security or to improve the functionality of our Service, or we are legally obligated to retain this data for longer time periods.</p>
                </div><div id="ie1c"><h1 style="text-align:justify"><strong>Transfer of Data</strong></h1>
                </div><div id="ijkuk"><p>Your information, including Personal Data, may be transferred to &ndash; and maintained on &ndash; computers located outside of your state, province, country or other governmental jurisdiction where the data protection laws may differ from those of your jurisdiction. Your consent to this Privacy Policy followed by your submission of such information represents your agreement to that transfer.<br />
                Artifism, Inc. will take all the steps reasonably necessary to ensure that your data is treated securely and in accordance with this Privacy Policy and no transfer of your Personal Data will take place to an organisation or a country unless there are adequate controls in place including the security of your data and other personal information.</p>
                </div><div id="ipwh"><h1 style="text-align:justify"><strong>Disclosure of Data</strong></h1>
                </div><div id="ihlvo"><p>We may disclose personal information that we collect, or you provide:</p>

                <p>&nbsp;</p>

                <p><strong>Disclosure for Law Enforcement.</strong><br />
                Under certain circumstances, we may be required to disclose your Personal Data if required to do so by law or in response to valid requests by public authorities.</p>

                <p>&nbsp;</p>

                <p><strong>Business Transaction.</strong><br />
                If we or our subsidiaries are involved in a merger, acquisition or asset sale, your Personal Data may be transferred.<br />
                Other cases. We may disclose your information also:</p>

                <p>&nbsp;</p>

                <p>to fulfill the purpose for which you provide it;<br />
                for the purpose of including your company&rsquo;s logo on our website;</p>

                <p>&nbsp;</p>

                <p>for any other purpose with your consent.</p>
                </div><div id="isrc5"><h1 style="text-align:justify"><strong>Security of Data</strong></h1>
                </div><div id="ijo7b"><p>The security of your data is important to us but remember that no method of transmission over the Internet or method of electronic storage is 100% secure. While we strive to use commercially acceptable means to protect your Personal Data, we cannot guarantee its absolute security.</p>
                </div><div id="ijnmf"><h1 style="text-align:justify"><strong>Your Data Protection Rights Under General Data Protection Regulation (GDPR)</strong></h1>
                </div><div id="ih0zr"><p>If you are a resident of the European Union (EU) and European Economic Area (EEA), you have certain data protection rights, covered by GDPR. &ndash; See more at https://eur-lex.europa.eu/eli/reg/2016/679/oj</p>

                <p>&nbsp;</p>

                <p>We aim to take reasonable steps to allow you to correct, amend, delete, or limit the use of your Personal Data.<br />
                If you wish to be informed what Personal Data we hold about you and if you want it to be removed from our systems, please email us at support@artifism.com.</p>

                <p>&nbsp;</p>

                <p>In certain circumstances, you have the following data protection rights:</p>

                <p>&nbsp;</p>

                <p>the right to access, update or to delete the information we have on you;<br />
                the right of rectification. You have the right to have your information rectified if that information is inaccurate or incomplete;<br />
                the right to object. You have the right to object to our processing of your Personal Data;<br />
                the right of restriction. You have the right to request that we restrict the processing of your personal information;<br />
                the right to data portability. You have the right to be provided with a copy of your Personal Data in a structured, machine-readable and commonly used format;<br />
                the right to withdraw consent. You also have the right to withdraw your consent at any time where we rely on your consent to process your personal information;</p>

                <p>&nbsp;</p>

                <p>Please note that we may ask you to verify your identity before responding to such requests. Please note, we may not able to provide Service without some necessary data.<br />
                You have the right to complain to a Data Protection Authority about our collection and use of your Personal Data. For more information, please contact your local data protection authority in the European Economic Area (EEA).</p>
                </div><div id="ivprk"><h1 style="text-align:justify"><strong>Service Providers</strong></h1>
                </div><div id="ivdq6"><p>We may employ third party companies and individuals to facilitate our Service (&ldquo;Service Providers&rdquo;), provide Service on our behalf, perform Service-related services or assist us in analysing how our Service is used.<br />
                These third parties have access to your Personal Data only to perform these tasks on our behalf and are obligated not to disclose or use it for any other purpose.</p>
                </div><div id="ifv2k"><h1 style="text-align:justify"><strong>CI/CD tools</strong></h1>
                </div><div id="igvdo"><p>We may use third-party Service Providers to automate the development process of our Service.<br />
                GitHub<br />
                GitHub is provided by GitHub, Inc.<br />
                GitHub is a development platform to host and review code, manage projects, and build software.<br />
                For more information on what data GitHub collects for what purpose and how the protection of the data is ensured, please visit GitHub Privacy Policy page: https://help.github.com/en/articles/github-privacy-statement.</p>
                </div><div id="iwrsl"><h1 style="text-align:justify"><strong>Behavioral Remarketing</strong></h1>
                </div><div id="izz1f"><p>Artifism, Inc. uses remarketing services to advertise on third party websites to you after you visited our Service. We and our third-party vendors use cookies to inform, optimize and serve ads based on your past visits to our Service.<br />
                GitHub is provided by GitHub, Inc.</p>

                <p>&nbsp;</p>

                <p><strong>Google Ads (AdWords)</strong><br />
                Google Ads (AdWords) remarketing service is provided by Google Inc.<br />
                You can opt-out of Google Analytics for Display Advertising and customize the Google Display Network ads by visiting the Google Ads Settings page: http://www.google.com/settings/ads<br />
                Google also recommends installing the Google Analytics Opt-out Browser Add-on &ndash; https://tools.google.com/dlpage/gaoptout &ndash; for your web browser. Google Analytics Opt-out Browser Add-on provides visitors with the ability to prevent their data from being collected and used by Google Analytics. For more information on the privacy practices of Google, please visit the Google Privacy Terms web page: https://policies.google.com/privacy?hl=en<br />
                For more information on the privacy practices of Google, please visit the Google Privacy Terms web page: https://policies.google.com/privacy?hl=en</p>

                <p>&nbsp;</p>

                <p><strong>Facebook</strong><br />
                Facebook remarketing service is provided by Facebook Inc.<br />
                Facebook remarketing service is provided by Facebook Inc. You can learn more about interest-based advertising from Facebook by visiting this page: https://www.facebook.com/help/164968693837950<br />
                To opt-out from Facebook&#39;s interest-based ads, follow these instructions from Facebook: https://www.facebook.com/help/568137493302217<br />
                Facebook adheres to the Self-Regulatory Principles for Online Behavioural Advertising established by the Digital Advertising Alliance. You can also opt-out from Facebook and other participating companies through the Digital Advertising Alliance in the USA http://www.aboutads.info/choices/, the Digital Advertising Alliance of Canada in Canada http://youradchoices.ca/ or the European Interactive Digital Advertising Alliance in Europe http://www.youronlinechoices.eu/, or opt-out using your mobile device settings.<br />
                For more information on the privacy practices of Facebook, please visit Facebook&#39;s Data Policy: https://www.facebook.com/privacy/explanation</p>
                </div><div id="i325j"><h1 style="text-align:justify"><strong>Payments</strong></h1>
                </div><div id="iajog"><p>We may provide paid products and/or services within Service. In that case, we use third-party services for payment processing (e.g. payment processors).<br />
                We will not store or collect your payment card details. That information is provided directly to our third-party payment processors whose use of your personal information is governed by their Privacy Policy. These payment processors adhere to the standards set by PCI-DSS as managed by the PCI Security Standards Council, which is a joint effort of brands like Visa, Mastercard, American Express and Discover. PCI-DSS requirements help ensure the secure handling of payment information.<br />
                The payment processors we work with are:</p>

                <p>&nbsp;</p>

                <p><strong>PayPal or Braintree:</strong><br />
                Their Privacy Policy can be viewed at https://www.paypal.com/webapps/mpp/ua/privacy-full</p>

                <p>&nbsp;</p>

                <p><strong>Stripe:</strong><br />
                Their Privacy Policy can be viewed at: https://stripe.com/us/privacy</p>
                </div><div id="ijco"><h1 style="text-align:justify"><strong>Links to Other Sites</strong></h1>
                </div><div id="imwjf"><p>Our Service may contain links to other sites that are not operated by us. If you click a third party link, you will be directed to that third party&#39;s site. We strongly advise you to review the Privacy Policy of every site you visit.<br />
                We have no control over and assume no responsibility for the content, privacy policies or practices of any third party sites or services.</p>
                </div><div id="ie4ia"><h1 style="text-align:justify"><strong>Changes to This Privacy Policy</strong></h1>
                </div><div id="ikrzn"><p>We may update our Privacy Policy from time to time. We will notify you of any changes by posting the new Privacy Policy on this page.<br />
                We will let you know via email and/or a prominent notice on our Service, prior to the change becoming effective and update &ldquo;effective date&rdquo; at the top of this Privacy Policy.<br />
                You are advised to review this Privacy Policy periodically for any changes. Changes to this Privacy Policy are effective when they are posted on this page.</p>
                </div><div id="i94k"><h1 style="text-align:justify"><strong>Contact Us</strong></h1>
                </div><div id="i1b2u"><p>If you have any questions about this Privacy Policy, please contact us:</p>

                <p>By email: support@artifism.com.</p>
                </div></body>',
                'meta_title' => 'About us',
                'meta_description' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum dapibus venenatis turpis vel vulputate. Donec in lacinia arcu. Aenean sapien magna, eleifend at gravida in, luctus a quam.',
                'status' => 'Active',
                'type' => 'page',
                'layout' => 'default',
                'default' => 0,
            ),
            1 =>
            array(
                'id' => 2,
                'name' => 'Privacy Policy',
                'slug' => 'privacy-policy',
                'css' => '* { box-sizing: border-box; } body {margin: 0;}',
                'description' => '<body id="idnh"><section class="bdg-sect"><p class="paragraph"><br />
                At Artifism, we are committed to protecting your privacy and ensuring the security of your personal information. This Privacy Policy outlines how we collect, use, disclose, and protect the information you provide when using our project, Artifism, which utilizes OpenAI technology. By using Artifism, you consent to the practices described in this Privacy Policy.<br />
                <br />
                <strong><big>Information We Collect:</big></strong><br />
                <br />
                <strong>1.1.</strong> Personal Information: When you interact with Artifism, we may collect certain personally identifiable information, including but not limited to your name, email address, and any additional information you voluntarily provide. We only collect personal information that is necessary to provide you with the services offered by Artifism.<br />
                <br />
                <strong>1.2.</strong> Usage Information: We may also collect non-personally identifiable information about your usage of Artifism, such as your IP address, device information, browser type, and operating system. This information is collected automatically and is used to improve the functionality and performance of Artifism.<br />
                Use of Information:<br />
                <br />
                <strong>2.1.</strong> Personal Information: We use the personal information we collect to provide and improve the services offered by Artifism. This includes responding to your inquiries, providing customer support, and delivering personalized content. We may also use your personal information to send you important updates and notifications about Artifism or promotional materials if you have opted-in to receive them.<br />
                <br />
                <strong>2.2.</strong> Usage Information: The non-personally identifiable information we collect is used for statistical purposes, to analyze trends, administer Artifism, and gather demographic information about our user base. This information helps us enhance the user experience, optimize Artifism&#39;s performance, and ensure the security of our systems.<br />
                <br />
                <big><strong>Information Sharing and Disclosure:</strong></big><br />
                <br />
                <strong>3.1. </strong>Third-Party Service Providers: We may share your personal information with trusted third-party service providers who assist us in operating Artifism, such as hosting providers, analytics providers, and customer support providers. These third parties are bound by confidentiality obligations and are only authorized to use your personal information as necessary to provide services to us.<br />
                <br />
                <strong>3.2. </strong>Legal Requirements: We may disclose your personal information if required by law, regulation, or legal process, or if we believe that such disclosure is necessary to protect our rights, enforce our Terms of Service, or respond to a legal request.<br />
                <br />
                <big><strong>Data Security:</strong></big><br />
                <br />
                We take reasonable measures to protect your personal information from unauthorized access, loss, misuse, or alteration. However, please note that no method of transmission over the internet or electronic storage is 100% secure. Therefore, while we strive to protect your personal information, we cannot guarantee its absolute security.<br />
                <br />
                <strong><big>Your Rights and Choices:</big></strong><br />
                <br />
                5.1. Access and Correction: You have the right to access, correct, or update your personal information held by us. You can do so by contacting us using the information provided at the end of this Privacy Policy.<br />
                <br />
                5.2. Opt-Out: If you no longer wish to receive promotional communications from us, you can opt-out by following the unsubscribe instructions provided in those communications.<br />
                <br />
                <strong><big>Third-Party Links:</big></strong><br />
                <br />
                Artifism may contain links to third-party websites or services that are not operated by us. This Privacy Policy does not apply to those third-party websites or services. We recommend reviewing the privacy policies of those third parties before interacting with them.<br />
                <br />
                <strong><big>Children&#39;s Privacy:</big></strong><br />
                <br />
                Artifism is not intended for individuals under the age of 18. We do not knowingly collect personal information from individuals under 18 years of age. If you believe we may have inadvertently collected information from a child under 18, please contact us using the information provided below, and we will promptly delete that information.<br />
                <br />
                <big><strong>Changes to this Privacy Policy:</strong></big><br />
                <br />
                We reserve the right to modify this Privacy Policy at any time. Any changes we make will be effective immediately upon posting the updated Privacy Policy on Artifism. We encourage you to review this Privacy Policy periodically to stay informed about our privacy practices.<br />
                <br />
                <big><strong>Contact Us:</strong></big><br />
                <br />
                If you have any questions or concerns about this Privacy Policy or our privacy practices, please contact us at [Insert contact information].<br />
                By using Artifism, you acknowledge that you have read, understood, and agreed to the terms of this Privacy Policy.<br />
                End of Privacy Policy.</p></section></body>',
                'meta_title' => 'Privacy Policy',
                'meta_description' => 'Protecting your privacy is our top priority. Discover how Artifism, powered by OpenAI, safeguards your personal information while providing an exceptional user experience. Read our privacy policy for transparency on data collection, usage, and security measures.',
                'status' => 'Active',
                'type' => 'page',
                'layout' => 'default',
                'default' => 0,
            ),
            2 =>
            array(
                'id' => 3,
                'name' => 'Refund Policy',
                'slug' => 'refund-policy',
                'css' => '* { box-sizing: border-box; } body {margin: 0;}#iz8k{padding:10px;margin:0 0 10px 0;}#ifjs{padding:10px;margin:0 0 30px 0;}#ijco{padding:10px;margin:0 0 10px 0;}#ik5t{padding:10px;margin:0 0 30px 0;}#inbk{padding:10px;margin:0 0 10px 0;}#ie1c{padding:10px;margin:0 0 10px 0;}#ipwh{padding:10px;margin:0 0 10px 0;}#icok{padding:10px;margin:0 0 10px 0;}#i94k{padding:10px;margin:0 0 10px 0;}#i1b2u{padding:10px;margin:0 0 30px 0;}#imwjf{padding:10px;margin:0 0 30px 0;}#ihlvo{padding:10px;margin:0 0 30px 0;}#ijkuk{padding:10px;margin:0 0 30px 0;}#ib7ow{padding:10px;margin:0 0 30px 0;}#izl75{padding:10px;margin:0 0 10px 0;}#iiluk{padding:10px;margin:0 0 30px 0;}#izhb9{padding:10px;margin:0 0 10px 0;}#i5bvu{padding:10px;margin:0 0 10px 0;}#iwi92{padding:10px;margin:0 0 30px 0;}#ieavt{padding:10px;margin:0 0 30px 0;}#i325j{padding:10px;margin:0 0 10px 0;}#iwrsl{padding:10px;margin:0 0 10px 0;}#ifv2k{padding:10px;margin:0 0 10px 0;}#ivprk{padding:10px;margin:0 0 10px 0;}#ijnmf{padding:10px;margin:0 0 10px 0;}#isrc5{padding:10px;margin:0 0 10px 0;}#iajog{padding:10px;margin:0 0 30px 0;}#izz1f{padding:10px;margin:0 0 30px 0;}#igvdo{padding:10px;margin:0 0 30px 0;}#ivdq6{padding:10px;margin:0 0 30px 0;}#ih0zr{padding:10px;margin:0 0 30px 0;}#ijo7b{padding:10px;margin:0 0 30px 0;}#ie4ia{padding:10px;margin:0 0 10px 0;}#ikrzn{padding:10px;margin:0 0 30px 0;}',
                'description' => '<body id="izt5"><div id="iz8k"><h1 style="text-align:justify"><strong>Introduction</strong></h1>
                </div><div id="ifjs"><p>Welcome to Artifism, Inc.<br />
                Artifism, Inc. (&ldquo;us&rdquo;, &ldquo;we&rdquo;, or &ldquo;our&rdquo;) operates https://demo.artifism.techvill.net/ (hereinafter referred to as &ldquo;Service&rdquo;).<br />
                Our Privacy Policy governs your visit to https://demo.artifism.techvill.net/, and explains how we collect, safeguard and disclose information that results from your use of our Service.<br />
                By using Service, you agree to the collection and use of information in accordance with this policy. Unless otherwise defined in this Privacy Policy, the terms used in this Privacy Policy have the same meanings as in our Terms and Conditions.<br />
                Our Terms and Conditions (&ldquo;Terms&rdquo;) govern all use of our Service and together with the Privacy Policy constitutes your agreement with us (&ldquo;agreement&rdquo;).</p>
                </div><div id="i5bvu"><h1 style="text-align:justify"><strong>Definitions</strong></h1>
                </div><div id="ieavt"><p>Service means the https://demo.artifism.techvill.net/ website operated by Artifism, Inc.<br />
                Personal Data means data about a living individual who can be identified from those data (or from those and other information either in our possession or likely to come into our possession).<br />
                Usage Data is data collected automatically either generated by the use of Service or from Service infrastructure itself (for example, the duration of a page visit).<br />
                Cookies are small files stored on your device (computer or mobile device).<br />
                Data Controller means a natural or legal person who (either alone or jointly or in common with other persons) determines the purposes for which and the manner in which any personal data are, or are to be, processed. For the purpose of this Privacy Policy, we are a Data Controller of your data.<br />
                Data Processors (on service providers) means any natural or legal person who processes the data on behalf of the Data Controller. We may use the services of various Service Providers in order to process your data more effectively.<br />
                Data Subject is any living individual who is the subject of Personal Data.<br />
                The User is the individual using our Service. The User corresponds to the Data Subject, who is the subject of Personal Data.</p>
                </div><div id="izhb9"><h1 style="text-align:justify"><strong>Information Collection and Use</strong></h1>
                </div><div id="iwi92"><p>We collect several different types of information for various purposes to provide and improve our Service to you.</p>
                </div><div id="izl75"><h1 style="text-align:justify"><strong>Types of Data Collected</strong></h1>
                </div><div id="iiluk"><p><strong>Personal Data</strong><br />
                While using our Service, we may ask you to provide us with certain personally identifiable information that can be used to contact or identify you (&ldquo;Personal Data&rdquo;). Personally identifiable information may include, but is not limited to:</p>

                <p>&nbsp;</p>

                <p>Email address<br />
                First name and last name<br />
                Cookies and Usage Data</p>

                <p>&nbsp;</p>

                <p>We may use your Personal Data to contact you with newsletters, marketing or promotional materials and other information that may be of interest to you. You may opt out of receiving any, or all, of these communications from us by following the unsubscribe link or by emailing at support@artifism.com.</p>

                <p>&nbsp;</p>

                <p><strong>Personal Data</strong><br />
                We may also collect information that your browser sends whenever you visit our Service or when you access Service by or through a mobile device (&ldquo;Usage Data&rdquo;).<br />
                This Usage Data may include information such as your computer&#39;s Internet Protocol address (e.g. IP address), browser type, browser version, the pages of our Service that you visit, the time and date of your visit, the time spent on those pages, unique device identifiers and other diagnostic data.<br />
                When you access Service with a mobile device, this Usage Data may include information such as the type of mobile device you use, your mobile device unique ID, the IP address of your mobile device, your mobile operating system, the type of mobile Internet browser you use, unique device identifiers and other diagnostic data.</p>

                <p>&nbsp;</p>

                <p><strong>Personal Data</strong><br />
                We use cookies and similar tracking technologies to track the activity on our Service and we hold certain information.<br />
                Cookies are files with a small amount of data which may include an anonymous unique identifier. Cookies are sent to your browser from a website and stored on your device. Other tracking technologies are also used such as beacons, tags and scripts to collect and track information and to improve and analyze our Service.<br />
                You can instruct your browser to refuse all cookies or to indicate when a cookie is being sent. However, if you do not accept cookies, you may not be able to use some portions of our Service.</p>

                <p>&nbsp;</p>

                <p>Examples of Cookies we use:<br />
                Session Cookies: We use Session Cookies to operate our Service.<br />
                Preference Cookies: We use Preference Cookies to remember your preferences and various settings.<br />
                Security Cookies: We use Security Cookies for security purposes.<br />
                Advertising Cookies: Advertising Cookies are used to serve you with advertisements that may be relevant to you and your interests.</p>
                </div><div id="icok"><h1 style="text-align:justify"><strong>Use of Data</strong></h1>
                </div><div id="ib7ow"><p>Artifism, Inc. uses the collected data for various purposes:</p>

                <p>&nbsp;</p>

                <p><strong>Personal Data</strong><br />
                to provide and maintain our Service;<br />
                to notify you about changes to our Service;<br />
                to allow you to participate in interactive features of our Service when you choose to do so;<br />
                to provide customer support;<br />
                to gather analysis or valuable information so that we can improve our Service;<br />
                to monitor the usage of our Service;<br />
                to detect, prevent and address technical issues;<br />
                to fulfill any other purpose for which you provide it;<br />
                to carry out our obligations and enforce our rights arising from any contracts entered into between you and us, including for billing and collection;<br />
                to provide you with notices about your account and/or subscription, including expiration and renewal notices, email-instructions, etc.;<br />
                to provide you with news, special offers and general information about other goods, services and events which we offer that are similar to those that you have already purchased or enquired about unless you have opted not to receive such information;<br />
                in any other way we may describe when you provide the information;<br />
                for any other purpose with your consent.</p>
                </div><div id="inbk"><h1 style="text-align:justify"><strong>Retention of Data</strong></h1>
                </div><div id="ik5t"><p>We will retain your Personal Data only for as long as is necessary for the purposes set out in this Privacy Policy. We will retain and use your Personal Data to the extent necessary to comply with our legal obligations (for example, if we are required to retain your data to comply with applicable laws), resolve disputes, and enforce our legal agreements and policies.<br />
                We will also retain Usage Data for internal analysis purposes. Usage Data is generally retained for a shorter period, except when this data is used to strengthen the security or to improve the functionality of our Service, or we are legally obligated to retain this data for longer time periods.</p>
                </div><div id="ie1c"><h1 style="text-align:justify"><strong>Transfer of Data</strong></h1>
                </div><div id="ijkuk"><p>Your information, including Personal Data, may be transferred to &ndash; and maintained on &ndash; computers located outside of your state, province, country or other governmental jurisdiction where the data protection laws may differ from those of your jurisdiction. Your consent to this Privacy Policy followed by your submission of such information represents your agreement to that transfer.<br />
                Artifism, Inc. will take all the steps reasonably necessary to ensure that your data is treated securely and in accordance with this Privacy Policy and no transfer of your Personal Data will take place to an organisation or a country unless there are adequate controls in place including the security of your data and other personal information.</p>
                </div><div id="ipwh"><h1 style="text-align:justify"><strong>Disclosure of Data</strong></h1>
                </div><div id="ihlvo"><p>We may disclose personal information that we collect, or you provide:</p>

                <p>&nbsp;</p>

                <p><strong>Disclosure for Law Enforcement.</strong><br />
                Under certain circumstances, we may be required to disclose your Personal Data if required to do so by law or in response to valid requests by public authorities.</p>

                <p>&nbsp;</p>

                <p><strong>Business Transaction.</strong><br />
                If we or our subsidiaries are involved in a merger, acquisition or asset sale, your Personal Data may be transferred.<br />
                Other cases. We may disclose your information also:</p>

                <p>&nbsp;</p>

                <p>to fulfill the purpose for which you provide it;<br />
                for the purpose of including your company&rsquo;s logo on our website;</p>

                <p>&nbsp;</p>

                <p>for any other purpose with your consent.</p>
                </div><div id="isrc5"><h1 style="text-align:justify"><strong>Security of Data</strong></h1>
                </div><div id="ijo7b"><p>The security of your data is important to us but remember that no method of transmission over the Internet or method of electronic storage is 100% secure. While we strive to use commercially acceptable means to protect your Personal Data, we cannot guarantee its absolute security.</p>
                </div><div id="ijnmf"><h1 style="text-align:justify"><strong>Your Data Protection Rights Under General Data Protection Regulation (GDPR)</strong></h1>
                </div><div id="ih0zr"><p>If you are a resident of the European Union (EU) and European Economic Area (EEA), you have certain data protection rights, covered by GDPR. &ndash; See more at https://eur-lex.europa.eu/eli/reg/2016/679/oj</p>

                <p>&nbsp;</p>

                <p>We aim to take reasonable steps to allow you to correct, amend, delete, or limit the use of your Personal Data.<br />
                If you wish to be informed what Personal Data we hold about you and if you want it to be removed from our systems, please email us at support@artifism.com.</p>

                <p>&nbsp;</p>

                <p>In certain circumstances, you have the following data protection rights:</p>

                <p>&nbsp;</p>

                <p>the right to access, update or to delete the information we have on you;<br />
                the right of rectification. You have the right to have your information rectified if that information is inaccurate or incomplete;<br />
                the right to object. You have the right to object to our processing of your Personal Data;<br />
                the right of restriction. You have the right to request that we restrict the processing of your personal information;<br />
                the right to data portability. You have the right to be provided with a copy of your Personal Data in a structured, machine-readable and commonly used format;<br />
                the right to withdraw consent. You also have the right to withdraw your consent at any time where we rely on your consent to process your personal information;</p>

                <p>&nbsp;</p>

                <p>Please note that we may ask you to verify your identity before responding to such requests. Please note, we may not able to provide Service without some necessary data.<br />
                You have the right to complain to a Data Protection Authority about our collection and use of your Personal Data. For more information, please contact your local data protection authority in the European Economic Area (EEA).</p>
                </div><div id="ivprk"><h1 style="text-align:justify"><strong>Service Providers</strong></h1>
                </div><div id="ivdq6"><p>We may employ third party companies and individuals to facilitate our Service (&ldquo;Service Providers&rdquo;), provide Service on our behalf, perform Service-related services or assist us in analysing how our Service is used.<br />
                These third parties have access to your Personal Data only to perform these tasks on our behalf and are obligated not to disclose or use it for any other purpose.</p>
                </div><div id="ifv2k"><h1 style="text-align:justify"><strong>CI/CD tools</strong></h1>
                </div><div id="igvdo"><p>We may use third-party Service Providers to automate the development process of our Service.<br />
                GitHub<br />
                GitHub is provided by GitHub, Inc.<br />
                GitHub is a development platform to host and review code, manage projects, and build software.<br />
                For more information on what data GitHub collects for what purpose and how the protection of the data is ensured, please visit GitHub Privacy Policy page: https://help.github.com/en/articles/github-privacy-statement.</p>
                </div><div id="iwrsl"><h1 style="text-align:justify"><strong>Behavioral Remarketing</strong></h1>
                </div><div id="izz1f"><p>Artifism, Inc. uses remarketing services to advertise on third party websites to you after you visited our Service. We and our third-party vendors use cookies to inform, optimize and serve ads based on your past visits to our Service.<br />
                GitHub is provided by GitHub, Inc.</p>

                <p>&nbsp;</p>

                <p><strong>Google Ads (AdWords)</strong><br />
                Google Ads (AdWords) remarketing service is provided by Google Inc.<br />
                You can opt-out of Google Analytics for Display Advertising and customize the Google Display Network ads by visiting the Google Ads Settings page: http://www.google.com/settings/ads<br />
                Google also recommends installing the Google Analytics Opt-out Browser Add-on &ndash; https://tools.google.com/dlpage/gaoptout &ndash; for your web browser. Google Analytics Opt-out Browser Add-on provides visitors with the ability to prevent their data from being collected and used by Google Analytics. For more information on the privacy practices of Google, please visit the Google Privacy Terms web page: https://policies.google.com/privacy?hl=en<br />
                For more information on the privacy practices of Google, please visit the Google Privacy Terms web page: https://policies.google.com/privacy?hl=en</p>

                <p>&nbsp;</p>

                <p><strong>Facebook</strong><br />
                Facebook remarketing service is provided by Facebook Inc.<br />
                Facebook remarketing service is provided by Facebook Inc. You can learn more about interest-based advertising from Facebook by visiting this page: https://www.facebook.com/help/164968693837950<br />
                To opt-out from Facebook&#39;s interest-based ads, follow these instructions from Facebook: https://www.facebook.com/help/568137493302217<br />
                Facebook adheres to the Self-Regulatory Principles for Online Behavioural Advertising established by the Digital Advertising Alliance. You can also opt-out from Facebook and other participating companies through the Digital Advertising Alliance in the USA http://www.aboutads.info/choices/, the Digital Advertising Alliance of Canada in Canada http://youradchoices.ca/ or the European Interactive Digital Advertising Alliance in Europe http://www.youronlinechoices.eu/, or opt-out using your mobile device settings.<br />
                For more information on the privacy practices of Facebook, please visit Facebook&#39;s Data Policy: https://www.facebook.com/privacy/explanation</p>
                </div><div id="i325j"><h1 style="text-align:justify"><strong>Payments</strong></h1>
                </div><div id="iajog"><p>We may provide paid products and/or services within Service. In that case, we use third-party services for payment processing (e.g. payment processors).<br />
                We will not store or collect your payment card details. That information is provided directly to our third-party payment processors whose use of your personal information is governed by their Privacy Policy. These payment processors adhere to the standards set by PCI-DSS as managed by the PCI Security Standards Council, which is a joint effort of brands like Visa, Mastercard, American Express and Discover. PCI-DSS requirements help ensure the secure handling of payment information.<br />
                The payment processors we work with are:</p>

                <p>&nbsp;</p>

                <p><strong>PayPal or Braintree:</strong><br />
                Their Privacy Policy can be viewed at https://www.paypal.com/webapps/mpp/ua/privacy-full</p>

                <p>&nbsp;</p>

                <p><strong>Stripe:</strong><br />
                Their Privacy Policy can be viewed at: https://stripe.com/us/privacy</p>
                </div><div id="ijco"><h1 style="text-align:justify"><strong>Links to Other Sites</strong></h1>
                </div><div id="imwjf"><p>Our Service may contain links to other sites that are not operated by us. If you click a third party link, you will be directed to that third party&#39;s site. We strongly advise you to review the Privacy Policy of every site you visit.<br />
                We have no control over and assume no responsibility for the content, privacy policies or practices of any third party sites or services.</p>
                </div><div id="ie4ia"><h1 style="text-align:justify"><strong>Changes to This Privacy Policy</strong></h1>
                </div><div id="ikrzn"><p>We may update our Privacy Policy from time to time. We will notify you of any changes by posting the new Privacy Policy on this page.<br />
                We will let you know via email and/or a prominent notice on our Service, prior to the change becoming effective and update &ldquo;effective date&rdquo; at the top of this Privacy Policy.<br />
                You are advised to review this Privacy Policy periodically for any changes. Changes to this Privacy Policy are effective when they are posted on this page.</p>
                </div><div id="i94k"><h1 style="text-align:justify"><strong>Contact Us</strong></h1>
                </div><div id="i1b2u"><p>If you have any questions about this Privacy Policy, please contact us:</p>

                <p>By email: support@artifism.com.</p>
                </div></body>',
                'meta_title' => NULL,
                'meta_description' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum dapibus venenatis turpis vel vulputate. Donec in lacinia arcu. Aenean sapien magna, eleifend at gravida in, luctus a quam.',
                'status' => 'Active',
                'type' => 'page',
                'layout' => 'default',
                'default' => 0,
            ),
            3 =>
            array(
                'id' => 4,
                'name' => 'Digital Payments',
                'slug' => 'digital-payments',
                'css' => '* { box-sizing: border-box; } body {margin: 0;}*{box-sizing:border-box;}body{margin:0;}.gjs-row{display:table;padding:10px;width:100%;}#ie0e{padding:30px 10px;text-align:justify;}',
                'description' => '<body><div id="idi5" class="gjs-row"><div id="ie0e"><p id="iurxl"><span id="i6ays"><span id="i5l6m"></span></span><span id="it00b"><span id="ike6m"></span></span><span id="i0wfh"><span id="i9v0z"></span></span></p><p id="im1kn"><br />
                Our digital payment system is designed to provide you with a seamless and secure payment experience. With Artifism, you can enjoy the convenience of using a wide range of trusted payment gateways. Our system supports popular payment processors such as AuthorizeNet, Instamojo, MtnMomo, Stripe, SslCommerz, NGenius, Paypal, Paystack, Paytm, and Razorpay.<br />
                <br />
                Here&#39;s a brief description of each supported payment gateway:<br />
                <strong>AuthorizeNet:</strong> AuthorizeNet is a popular payment gateway that enables businesses to accept credit card payments securely. It provides robust fraud detection tools and advanced security features to protect sensitive customer data.<br />
                <br />
                <strong>CheckPayments:</strong> CheckPayments is a payment gateway that allows businesses to accept payments via checks. It provides a convenient way for customers to make payments using traditional paper checks while automating the check processing and verification process.<br />
                <br />
                <strong>Instamojo:</strong> Instamojo is a leading Indian payment gateway that supports multiple payment methods, including credit cards, debit cards, and mobile wallets. It offers easy integration, reliable payment processing, and comprehensive reporting features.<br />
                <br />
                <strong>MtnMomo:</strong> MtnMomo is a mobile money payment gateway widely used in Africa. It enables users to make payments and transfer funds securely using their mobile phones and M-Pesa accounts.<br />
                StripeRecurring: StripeRecurring is a payment gateway that specializes in handling recurring payments. It offers businesses the ability to set up and manage subscriptions, membership fees, and other recurring billing models with ease.<br />
                <br />
                <strong>Stripe:</strong> Stripe is a globally recognized payment gateway that supports online payments with credit cards, debit cards, and digital wallets. It offers a developer-friendly platform, robust security, and extensive customization options.<br />
                <br />
                <strong>SslCommerz:</strong> SslCommerz is a popular payment gateway in Bangladesh. It supports various payment methods and offers seamless integration, secure transactions, and comprehensive transaction reporting.<br />
                <br />
                <strong>NGenius:</strong> NGenius is a payment gateway by Worldline that provides secure and reliable payment processing services. It supports a wide range of payment methods and offers advanced reporting and analytics features for businesses.<br />
                <br />
                <strong>Paypal: </strong>Paypal is a widely used global payment gateway that allows users to make online payments using their Paypal account, credit cards, or bank accounts. It offers a trusted and secure platform for transactions.<br />
                <br />
                <strong>PaypalRecurring:</strong> PaypalRecurring is a Paypal service specifically designed for managing and processing recurring payments. It simplifies the setup and management of subscription-based services and recurring billing cycles.<br />
                <br />
                <strong>Paystack: </strong>Paystack is a Nigerian payment gateway that enables businesses to accept online payments via various channels, including cards, bank transfers, and mobile money. It offers seamless integration, reliable transaction processing, and detailed reporting.<br />
                <br />
                <strong>Paytm:</strong> Paytm is a leading Indian payment gateway that supports online payments through multiple channels, including credit cards, debit cards, UPI, and mobile wallets. It provides a user-friendly interface and robust security measures.<br />
                <br />
                <strong>Razorpay:</strong> Razorpay is an Indian payment gateway that offers businesses a comprehensive solution for accepting online payments. It supports various payment methods and provides advanced features like smart routing, fraud prevention, and subscription management.<br />
                <br />
                Each of these payment gateways brings unique features and capabilities, allowing businesses to offer diverse payment options to their customers while ensuring the security and reliability of transactions. Our digital payment system seamlessly integrates with these gateways, empowering you to choose the payment methods that best suit your needs and preferences.<br />
                <br />
                Whether you prefer traditional payment methods like credit cards or cutting-edge options such as mobile wallets, our system has you covered. By integrating with multiple payment gateways, we offer you the flexibility to choose the payment method that suits your needs best.<br />
                <br />
                When it comes to security, we take your financial information seriously. Our digital payment system employs advanced encryption technology to protect your sensitive data during transmission. We adhere to strict industry standards to ensure that your payment details are kept confidential and secure.<br />
                <br />
                With Artifism&#39;s digital payment system, you can confidently make transactions with peace of mind, knowing that your information is handled with the utmost care. Experience the convenience, reliability, and security that our system provides, making your payment process smooth and hassle-free.<br />
                &nbsp;</p><p><span id="i5rnc"><span id="ibhli"></span></span><span id="ikb37"><span id="ie9me"></span></span></p><p><span id="if2hj"><span id="idsx1"></span></span></p><p id="itufe"><span id="i4egb"><span id="i0ffn"></span></span><span id="irox5"><span id="ighpw"></span></span></p><p><span id="ieu86"><span id="ik65k"></span></span></p><p><span id="ijpuw"><span id="ix01x"></span></span></p></div></div></body>',
                'meta_title' => 'Cras maximus pretium finibus.',
                'meta_description' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum dapibus venenatis turpis vel vulputate. Donec in lacinia arcu. Aenean sapien magna, eleifend at gravida in, luctus a quam.',
                'status' => 'Active',
                'type' => 'page',
                'layout' => 'default',
                'default' => 0,
            ),
            8 =>
            array(
                'id' => 9,
                'name' => 'Contact Us',
                'slug' => 'contact-us',
                'css' => '* { box-sizing: border-box; } body {margin: 0;}*{box-sizing:border-box;}body{margin:0;}#ie3j{justify-content:space-between;}#i77dl{border-radius:12px 12px 12px 12px;display:block;}#ifk9{margin:20px 0 50px 0;}#iv0vc{font-size:42px;font-weight:700;display:flex;line-height:55px;margin:14px 0 0 0;}.pl-1{color:#ff9c00;}#iwjhg{font-size:18px;line-height:27px;margin:5px 0 0 0;}#iegke{background-color:#f4f4f4;border-radius:12px 12px 12px 12px;padding:32px 0 32px 32px;margin:36px 0 0 0;}#ivthu{font-size:18px;line-height:23px;color:#2c2c2c;font-weight:700;}#iyxqs{display:flex;}#i5xny{width:2px;height:23px;background-color:#fcca19;margin:0 8px 0 0;}#i9udb{margin:15px 0 0 0;font-size:16px;line-height:26px;color:#898989;font-weight:500;}#iwe8p{display:flex;margin:26px 0 0 0;}#i8b9g{display:flex;margin:26px 0 0 0;}#izb5k{color:black;background-color:#fcca19;padding:12px 12px 12px 12px;border-radius:4px 4px 4px 4px;margin:0 18px 0 0;}#ih8cs{font-size:16px;line-height:25px;color:#2c2c2c;font-weight:500;}#ifd56{display:flex;margin:30px 0 0 0;}#i4nzf{padding:12px 12px 12px 12px;background-color:#fcca19;margin:0 18px 0 0;border-radius:4px 4px 4px 4px;}#i6op6{font-size:16px;line-height:24px;font-weight:500;color:#2c2c2c;display:flex;}#iy44j{padding:12px 12px 12px 12px;background-color:#fcca19;border-radius:4px 4px 4px 4px;margin:0 18px 0 0;}#i3emb{font-size:16px;line-height:24px;font-weight:500;color:#2c2c2c;display:flex;}#ieftr{width:2px;height:23px;background-color:#fcca19;margin:0 8px 0 0;}#ispie{display:flex;}#ig3w7{font-size:18px;line-height:23px;font-weight:700;color:#2c2c2c;}#i3d0h{color:black;}#i6l6k{color:black;}#i1oew{color:black;}#i0c3t{color:black;}#iwh9j{color:black;}#i3h7a{color:black;}',
                'description' => '<body><div id="ifk9"><div id="ie3j" class="grid mx-4 gap-5 grid-cols-1 lg:grid-cols-2"><div id="i5jk"><div id="i6n37"><div class="mt-20"><nav aria-label="Breadcrumb" class="text-sm"><ol class="list-none p-0 flex flex-wrap md:inline-flex text-xs md:text-sm roboto-medium font-medium text-gray-10 leading-5"><li class="flex items-center"><svg width="13" height="15" viewBox="0 0 13 15" fill="none" xmlns="http://www.w3.org/2000/svg" class="-mt-1 mr-2"><path fill-rule="evenodd" clip-rule="evenodd" d="M5.35643 1.89407C4.93608 2.1717 4.43485 2.59943 3.69438 3.23412L2.916 3.9013C2.0595 4.63545 1.82512 4.85827 1.69934 5.13174C1.57357 5.4052 1.55692 5.72817 1.55692 6.85625V10.1569C1.55692 10.9127 1.55857 11.4013 1.60698 11.7613C1.65237 12.099 1.72565 12.2048 1.7849 12.264C1.84416 12.3233 1.94997 12.3966 2.28759 12.442C2.64759 12.4904 3.13619 12.492 3.89206 12.492H8.56233C9.31819 12.492 9.80679 12.4904 10.1668 12.442C10.5044 12.3966 10.6102 12.3233 10.6695 12.264C10.7287 12.2048 10.802 12.099 10.8474 11.7613C10.8958 11.4013 10.8975 10.9127 10.8975 10.1569V6.85625C10.8975 5.72817 10.8808 5.4052 10.755 5.13174C10.6293 4.85827 10.3949 4.63545 9.53838 3.9013L8.76 3.23412C8.01953 2.59943 7.5183 2.1717 7.09795 1.89407C6.69581 1.62848 6.44872 1.55676 6.22719 1.55676C6.00566 1.55676 5.75857 1.62848 5.35643 1.89407ZM4.49849 0.595063C5.03749 0.239073 5.5849 0 6.22719 0C6.86948 0 7.41689 0.239073 7.95589 0.595063C8.4674 0.932894 9.04235 1.42573 9.7353 2.01972L10.5515 2.71933C10.5892 2.75162 10.6264 2.78347 10.6632 2.81492C11.3564 3.40806 11.8831 3.85873 12.1694 4.48124C12.4557 5.10375 12.4551 5.79693 12.4543 6.70926C12.4543 6.75764 12.4542 6.80662 12.4542 6.85625L12.4542 10.2081C12.4543 10.8981 12.4543 11.4927 12.3903 11.9688C12.3217 12.479 12.167 12.9681 11.7703 13.3648C11.3736 13.7615 10.8845 13.9162 10.3742 13.9848C9.89812 14.0488 9.30358 14.0488 8.61355 14.0488H3.84083C3.1508 14.0488 2.55626 14.0488 2.08015 13.9848C1.56991 13.9162 1.08082 13.7615 0.68411 13.3648C0.2874 12.9681 0.132701 12.479 0.064101 11.9688C9.07021e-05 11.4927 0.000124017 10.8981 0.000162803 10.2081L0.000164659 6.85625C0.000164659 6.80662 0.000122439 6.75763 8.07765e-05 6.70926C-0.000705247 5.79693 -0.00130245 5.10374 0.285011 4.48124C0.571324 3.85873 1.09802 3.40806 1.79122 2.81492C1.82798 2.78347 1.8652 2.75162 1.90288 2.71933L2.68126 2.05215C2.69391 2.0413 2.70652 2.03049 2.71909 2.01972C3.41204 1.42573 3.98698 0.932893 4.49849 0.595063Z" fill="#898989"></path><path fill-rule="evenodd" clip-rule="evenodd" d="M3.50293 9.37853C3.50293 8.51876 4.19991 7.82178 5.05969 7.82178H7.39482C8.25459 7.82178 8.95158 8.51876 8.95158 9.37853V13.2704C8.95158 13.7003 8.60309 14.0488 8.1732 14.0488C7.74331 14.0488 7.39482 13.7003 7.39482 13.2704V9.37853H5.05969V13.2704C5.05969 13.7003 4.71119 14.0488 4.28131 14.0488C3.85142 14.0488 3.50293 13.7003 3.50293 13.2704V9.37853Z" fill="#898989"></path></svg><a href=".." id="il2mk">Home</a><p class="px-2">/</p></li><li><a href="javascript:void(0)" aria-current="page" class="text-gray-12">Contact Us</a></li></ol></nav></div><div id="iv0vc" class="dm-bold"><div id="iia7g"><p>GET IN</p></div><div id="ieeak" class="pl-1"><p>TOUCH</p></div></div><div id="iwwrv"></div></div><div id="iwjhg" class="dm-regular"><p>If you have any queries, concerns or suggestions,<br/>
please contact us.</p></div><div id="i6uxw"><div id="iegke"><div id="iyxqs"><div id="i5xny"></div><div id="ivthu" class="dm-bold"><p>HEADQUARTERS</p></div></div><div id="i9udb" class="dm-sans"><p>Our team of professionals are live 24/7 and are<br/>
ready to help you get to your query.</p></div><div id="iyptk"><div id="ifd56"><div id="i8jf9"><img src="../public/uploads/20221114/84214fc7d8147f994367bad5e360fb05.png" id="izb5k"/></div><div id="i093w"></div><div id="ih8cs" class="dm-sans"><p>184 Main Rd E, St Albans, San Francisco,<br/>
United States of America.</p></div></div></div><div id="iqfkw"><div id="i8b9g"><div id="ip87f"></div><div id="i7yhb"><img id="i4nzf" src="../public/uploads/20221114/d3d95c9685b6785cdaabc5ea207175af.png"/></div><div id="i6op6" class="dm-sans items-center"><p>+46 963 350 1945, +46 746 346 84663</p></div></div></div><div id="i0bic"><div id="iwe8p"><div id="ikkkq"></div><div id="i5le6"><img id="iy44j" src="../public/uploads/20221114/82f880076d18bafc3bdb1fdd7988f547.png"/></div><div id="i3emb" class="items-center"><p>support@techvill.net</p></div></div></div><div id="ispie" class="mt-14"><div id="ieftr"></div><div id="ig3w7" class="dm-bold uppercase"><p>follow us on</p></div></div><div id="ige2g" class="flex gap-5 items-center mt-5"><a href="https://www.youtube.com/" target="_blank"><img id="i0c3t" src="../public/uploads/20221114/4212b4d6425b622bf5391387b5446cea.png"/></a><a href="https://www.pinterest.com/" target="_blank"><img id="i1oew" src="../public/uploads/20221114/b4bf139f125acf287becce5bbb4c96f6.png"/></a><a href="https://www.facebook.com/" target="_blank"><img id="i3d0h" src="../public/uploads/20221114/d509d72e02f0391123fc304d8b4fae99.png"/></a><a href="https://twitter.com/" target="_blank"><img id="i6l6k" src="../public/uploads/20221114/cf2e05536d870bf7dd728006ec4f0293.png"/></a><a href="https://www.messenger.com/" target="_blank"><img id="i3h7a" src="../public/uploads/20221114/c9d20e7377473a90fdcb58637f74c458.png"/></a><a href="https://www.instagram.com/" target="_blank"><img id="iwh9j" src="../public/uploads/20221114/fff0c6e58139ddbfc3c8ff2980db1b1e.png"/></a></div></div></div></div><img id="i77dl" src="../public/uploads/20221114/2e782eb90a0f43efbcd964050fbd8929.png" class="w-full h-full"/></div></div></body>',
                'meta_title' => '',
                'meta_description' => '',
                'status' => 'Active',
                'type' => 'page',
                'layout' => 'default',
                'default' => 0,
                ),

            9 =>
            array(
                'id' => 10,
                'name' => 'Terms',
                'slug' => 'terms',
                'css' => '* { box-sizing: border-box; } body {margin: 0;}#iz8k{padding:10px;margin:0 0 10px 0;}#ifjs{padding:10px;margin:0 0 30px 0;}#ijco{padding:10px;margin:0 0 10px 0;}#ik5t{padding:10px;margin:0 0 30px 0;}#inbk{padding:10px;margin:0 0 10px 0;}#ie1c{padding:10px;margin:0 0 10px 0;}#ipwh{padding:10px;margin:0 0 10px 0;}#icok{padding:10px;margin:0 0 10px 0;}#i94k{padding:10px;margin:0 0 10px 0;}#i1b2u{padding:10px;margin:0 0 30px 0;}#imwjf{padding:10px;margin:0 0 30px 0;}#ihlvo{padding:10px;margin:0 0 30px 0;}#ijkuk{padding:10px;margin:0 0 30px 0;}#ib7ow{padding:10px;margin:0 0 30px 0;}#izl75{padding:10px;margin:0 0 10px 0;}#iiluk{padding:10px;margin:0 0 15px 0;}#izhb9{padding:10px;margin:0 0 10px 0;}#i5bvu{padding:10px;margin:0 0 10px 0;}#iwi92{padding:10px;margin:0 0 30px 0;}#ieavt{padding:10px;margin:0 0 30px 0;}#i325j{padding:10px;margin:0 0 10px 0;}#iwrsl{padding:10px;margin:0 0 10px 0;}#ifv2k{padding:10px;margin:0 0 10px 0;}#ivprk{padding:10px;margin:0 0 10px 0;}#ijnmf{padding:10px;margin:0 0 10px 0;}#isrc5{padding:10px;margin:0 0 10px 0;}#iajog{padding:10px;margin:0 0 30px 0;}#izz1f{padding:10px;margin:0 0 30px 0;}#igvdo{padding:10px;margin:0 0 30px 0;}#ivdq6{padding:10px;margin:0 0 30px 0;}#ih0zr{padding:10px;margin:0 0 30px 0;}#ijo7b{padding:10px;margin:0 0 30px 0;}#ie4ia{padding:10px;margin:0 0 10px 0;}#ikrzn{padding:10px;margin:0 0 30px 0;}',
                'description' => '<body id="izt5"><div id="iz8k">
                <div id="iiluk"><p><strong>
                Acceptance of Terms
                </strong><br />
                By accessing or using our AI project, you agree to be bound by these Terms and Conditions. If you do not agree with any part of these terms, please refrain from using the AI project.
                </p></div>

                <div id="iiluk"><p><strong>
                Use of AI Project
                </strong><br />
                You may use the AI project for lawful purposes and in compliance with all applicable laws and regulations. Any unauthorized or illegal use of the AI project is strictly prohibited.
                </p></div>

                <div id="iiluk"><p><strong>
                Intellectual Property
                </strong><br />
                All intellectual property rights related to the AI project, including but not limited to software, algorithms, designs, trademarks, and content, are owned by or licensed to us. You agree not to infringe upon or misappropriate any intellectual property rights associated with the AI project.
                </p></div>

                <div id="iiluk"><p><strong>
                Data Privacy
                </strong><br />
                Our AI project may collect and process data in accordance with our Privacy Policy. By using the AI project, you consent to the collection, storage, and use of your data as described in the Privacy Policy.
                </p></div>

                <div id="iiluk"><p><strong>
                Disclaimer of Warranties
                </strong><br />
                The AI project is provided on an "as is" basis without any warranties or representations, express or implied. We do not guarantee the accuracy, reliability, or availability of the AI project and disclaim any liability for errors or interruptions.
                </p></div>

                <div id="iiluk"><p><strong>
                Limitation of Liability
                </strong><br />
                In no event shall we be liable for any direct, indirect, incidental, consequential, or punitive damages arising out of or in connection with the AI project or your use of it. This includes any damages resulting from loss of data, profits, or business interruption.
                </p></div>

                <div id="iiluk"><p><strong>
                Modification of Terms
                </strong><br />
                We reserve the right to modify or update these Terms and Conditions at any time without prior notice. It is your responsibility to review the terms periodically. Continued use of the AI project after any modifications indicates your acceptance of the updated terms.
                </p></div>

                <div id="iiluk"><p><strong>
                Termination
                </strong><br />
                We may suspend or terminate your access to the AI project at our discretion, without prior notice or liability, for any reason, including but not limited to a violation of these Terms and Conditions.
                </p></div>

                <div id="iiluk"><p><strong>
                Governing Law
                </strong><br />
                These Terms and Conditions shall be governed by and construed in accordance with the laws of [Jurisdiction]. Any disputes arising out of or in connection with these terms shall be subject to the exclusive jurisdiction of the courts in [Jurisdiction].
                </p></div>
                </div></body>',
                'meta_title' => 'Artifism',
                'meta_description' => '',
                'status' => 'Active',
                'type' => 'page',
                'layout' => 'default',
                'default' => 0,
            ),
        ));
    }
}
