@extends('errors.minimal-layout')
@section('title', '503 ' . __('Service Unavailable'))
@section('code', '503')
@section('name', __('Service Unavailable'))
@section('message', __('The server is currently unavailable'))
